import { PostTypeKeys } from '@/components/socialPost/templates_customizable_elements/theme_elements';
import { SocialPostThemeElements } from '@/components/socialPost/templates_customizable_elements/theme_elements';

export const Classic_SocialPost_TemplateThemeConfig: {
	[key in PostTypeKeys]?: SocialPostThemeElements;
} = {
	casual_topic: {
		useIllustraion: false,
		topicCSS: {
			fontSize: '30pt',
			fontWeight: 'bold',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'Georgia',
			letterSpacing: '-1.04px',
		},
		userNameCSS: {
			fontSize: '12pt',
			fontWeight: 'normal',
			lineHeight: 'normal',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'DM Sans Regular',
			letterSpacing: '1.08px',
		},
		subtopicCSS: {
			fontSize: '20pt',
			fontWeight: 'bold',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'Georgia',
			letterSpacing: '-1.04px',
		},
		contentCSS: {
			fontSize: '12pt',
			fontWeight: 'normal',
			lineHeight: 'normal',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'DM Sans Medium',
			letterSpacing: '1.08px',
		},
		lastPageContentCSS: {
			fontSize: '20pt',
			fontWeight: 'normal',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'DM Sans Bold',
			letterSpacing: '-1.04px',
		},
		lastPageTitleCSS: {
			fontSize: '30pt',
			fontWeight: 'bold',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'Georgia',
			letterSpacing: '-1.04px',
		},
	},
	serious_subject: {
		useIllustraion: false,
		// originalTitleCoverCSS: {
		// 	color: '#1B1C22',
		// 	fontWeight: 'bold',
		// 	fontSize: '24pt',
		// 	fontFamily: 'Arimo',
		// },
		originalTitleCoverCSS: {
			fontSize: '30pt',
			fontWeight: 'bold',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'Georgia',
			letterSpacing: '-1.04px',
		},
		// originalTitleCSS: {
		// 	color: 'rgba(27, 27, 27, 0.50)',
		// 	fontFamily: 'Nunito',
		// 	fontSize: '10pt',
		// 	fontStyle: 'bold',
		// },
		// briefCSS: {
		// 	fontSize: '10pt',
		// 	color: '#1B1B1B',
		// 	fontFamily: 'Nunito',
		// 	letterSpacing: '0.48px',
		// 	fontWeight: 'normal',
		// },
		briefCSS: {
			fontSize: '8pt',
			fontWeight: 'normal',
			lineHeight: 'normal',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'DM Sans Medium',
			letterSpacing: '1.08px',
		},
		// sectionTitleCSS: {
		// 	fontSize: '16pt',
		// 	fontWeight: 'bold',
		// 	color: '#1B1B1B',
		// 	fontFamily: 'Nunito',
		// },
		sectionTitleCSS: {
			fontSize: '20pt',
			fontWeight: 'bold',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'Georgia',
			letterSpacing: '-1.04px',
		},
		// contentCSS: {
		// 	fontSize: '10pt',
		// 	color: '#1B1B1B',
		// 	fontFamily: 'Nunito',
		// 	letterSpacing: '0.48px',
		// 	fontWeight: 'normal',
		// },
		contentCSS: {
			fontSize: '8pt',
			fontWeight: 'normal',
			lineHeight: 'normal',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'DM Sans Medium',
			letterSpacing: '1.08px',
		},
		// userNameCSS: {
		// 	fontSize: '9pt',
		// 	color: '#DAE9EA',
		// 	backgroundColor: '#1B1B1B',
		// 	borderRadius: '16px',
		// 	lineHeight: '25.126px',
		// 	letterSpacing: '0.628px',
		// 	fontFamily: 'Arimo',
		// 	fontWeight: 'normal',
		// },
		userNameCSS: {
			fontSize: '12pt',
			fontWeight: 'normal',
			lineHeight: 'normal',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'DM Sans Regular',
			letterSpacing: '1.08px',
		},
		lastPageContentCSS: {
			fontSize: '20pt',
			fontWeight: 'normal',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'DM Sans Bold',
			letterSpacing: '-1.04px',
		},
		lastPageTitleCSS: {
			fontSize: '30pt',
			fontWeight: 'bold',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'Georgia',
			letterSpacing: '-1.04px',
		},
	},
	reading_notes: {
		useIllustraion: false,
		readingtitleCSS: {
			// color: '#121212',
			// fontFamily: 'Cormorant',
			// fontSize: '45pt',
			// textAlign: 'center',
			// fontWeight: 'normal',
			fontSize: '30pt',
			fontWeight: 'bold',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'Georgia',
			letterSpacing: '-1.04px',
		},
		quoteCSS: {
			// color: '#1D222A',
			// fontFamily: 'Cormorant',
			// fontSize: '13pt',
			// lineHeight: '155%',
			// textAlign: 'center',
			// fontWeight: 'bold',
			fontSize: '20pt',
			fontWeight: 'bold',
			lineHeight: 'normal',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'Georgia',
			letterSpacing: '-1.04px',
		},
		sourceCSS: {
			// color: '#3A3A3A',
			// fontFamily: 'Cormorant',
			// fontSize: '13pt',
			// lineHeight: '222%',
			// textAlign: 'center',
			// fontWeight: 'bold',
			fontSize: '14pt',
			fontWeight: 'normal',
			lineHeight: 'normal',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'DM Sans Regular',
			letterSpacing: '1.08px',
		},
		userNameCSS: {
			fontSize: '12pt',
			fontWeight: 'normal',
			lineHeight: 'normal',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'DM Sans Regular',
			letterSpacing: '1.08px',
		},
		lastPageContentCSS: {
			fontSize: '20pt',
			fontWeight: 'normal',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'DM Sans Bold',
			letterSpacing: '-1.04px',
		},
		lastPageTitleCSS: {
			fontSize: '30pt',
			fontWeight: 'bold',
			lineHeight: 'normal',
			// fontStyle: 'italic',
			textAlign: 'left',
			color: '#333330',
			fontFamily: 'Georgia',
			letterSpacing: '-1.04px',
		},
	},
};
