import {
	SocialPostLayoutElements,
	SocialPostLayoutKeys,
} from '../../socialPostLayouts';

export const Default_SocialPost_TemplateLayoutsConfig: {
	[key in SocialPostLayoutKeys]: SocialPostLayoutElements;
} = {
	//casual
	Col_2_img_1_left_casual_topic: {
		canvasCSS: {
			width: '100%',
			height: '100%',
			background: '#F1F1F1',
			border: 'none',
		},
		columnCSS: {
			padding: '100px 40px 100px 40px',
			display: 'flex',
			flexDirection: 'column',
			gap: '20px',
			height: '100%',
			width: '100%',
			justifyContent: 'center',
			alignItems: 'center',
		},
		horizontalDividerCSS: {
			display: 'none',
		},
		pageNumberIndexCSS: {
			color: '#F5F1E2',
			fontFamily: 'Georgia',
			fontSize: '42px',
			fontStyle: 'normal',
			fontWeight: 400,
			lineHeight: 'normal',
		},
		pageNumberIndexContainerCSS: {
			display: 'none',
			// display: 'flex',
			// width: '68px',
			// height: '68px',
			// gap: '8px',
			// padding: '14px 10px 22px 10px',
			// justifyContent: 'center',
			// alignItems: 'center',
			// borderRadius: '999px',
			// border: '2px solid #333330',
			// background: '#333330',
			// alignSelf: 'center',
			// zIndex: 30,
			// position: 'absolute',
			// top: '160px',
		},
		subtopicCSS: {
			position: 'relative',
			zIndex: 30,
			paddingLeft: '40px',
			paddingRight: '40px',
			maxHeight: '65px',
			marginTop: '200px',
			textAlign: 'center',
		},
		imageAndTextContentContainerCSS: {
			// display: 'flex',
			// flexDirection: 'row',
			// display: 'grid',
			// gridTemplateColumns: 'repeat(2, minmax(0,1fr))', //
			// gap: '4px',
			width: '100%',
			// background: 'transparent',
			// marginTop: '34px',
			// height: '200px',
			// maxHeight: '400px',
		},
		imageContainerCSS: {
			// order: 0,
			// width: '100%',
			// height: '100%',
			position: 'absolute',
			height: '200px',
			width: '300px', // equivalent to w-full
			left: '50%',
			top: '25%',
			transform: 'translate(-50%, -50%)',
			background: 'transparent',
			// borderRadius:
			// 	'var(--radius-none, 0px) var(--radius-none, 0px) 96px var(--radius-none, 0px)',
			// border: '10px solid black',
		},

		contentCSS: {
			display: 'flex',
			flexDirection: 'column',
			gap: '10px',
			order: 1,
			maxHeight: '225px',
			// overflow: 'scroll', // if set, will cause editor tooltip hidden
			// marginTop: '34px',
			textAlign: 'center',
			alignItems: 'center',
		},
		logoCSS: {
			zIndex: 30,
			position: 'relative',
			alignSelf: 'flex-end',
			maxWidth: '100px',
		},
	},
	Col_2_img_1_right_casual_topic: {
		canvasCSS: {
			width: '100%',
			height: '100%',
			background: '#F1F1F1',
			border: 'none',
		},
		columnCSS: {
			padding: '100px 40px 100px 40px',
			display: 'flex',
			flexDirection: 'column',
			gap: '20px',
			height: '100%',
			width: '100%',
			justifyContent: 'center',
			alignItems: 'center',
		},
		horizontalDividerCSS: {
			display: 'none',
		},
		pageNumberIndexCSS: {
			color: '#F5F1E2',
			fontFamily: 'Georgia',
			fontSize: '42px',
			fontStyle: 'normal',
			fontWeight: 400,
			lineHeight: 'normal',
		},
		pageNumberIndexContainerCSS: {
			display: 'none',
			// display: 'flex',
			// width: '68px',
			// height: '68px',
			// gap: '8px',
			// padding: '14px 10px 22px 10px',
			// justifyContent: 'center',
			// alignItems: 'center',
			// borderRadius: '999px',
			// border: '2px solid #333330',
			// background: '#333330',
			// alignSelf: 'center',
			// zIndex: 30,
			// position: 'absolute',
			// top: '160px',
		},
		subtopicCSS: {
			position: 'relative',
			zIndex: 30,
			paddingLeft: '40px',
			paddingRight: '40px',
			maxHeight: '65px',
			marginTop: '200px',
			textAlign: 'center',
		},
		imageAndTextContentContainerCSS: {
			// display: 'flex',
			// flexDirection: 'row',
			// display: 'grid',
			// gridTemplateColumns: 'repeat(2, minmax(0,1fr))', //
			// gap: '4px',
			width: '100%',

			// marginTop: '34px',
			// height: '200px',
			// maxHeight: '400px',
		},
		imageContainerCSS: {
			// order: 0,
			// width: '100%',
			// height: '100%',
			position: 'absolute',
			height: '200px',
			width: '300px', // equivalent to w-full
			left: '50%',
			top: '25%',
			transform: 'translate(-50%, -50%)',
			background: 'transparent',
			// borderRadius:
			// 	'var(--radius-none, 0px) var(--radius-none, 0px) 96px var(--radius-none, 0px)',
			// border: '10px solid black',
		},

		contentCSS: {
			display: 'flex',
			flexDirection: 'column',
			gap: '10px',
			order: 1,
			maxHeight: '225px',
			// overflow: 'scroll', // if set, will cause editor tooltip hidden
			// marginTop: '34px',
			textAlign: 'center',
			alignItems: 'center',
		},
		logoCSS: {
			zIndex: 30,
			position: 'relative',
			alignSelf: 'flex-end',
			maxWidth: '100px',
		},
	},
	Col_1_img_0_casual_topic: {
		canvasCSS: {
			width: '100%',
			height: '100%',
			background: '#F1F1F1',
			border: 'none',
		},
		horizontalDividerCSS: {
			display: 'none',
		},
		pageNumberIndexCSS: {
			color: '#F5F1E2',
			fontFamily: 'Georgia',
			fontSize: '42px',
			fontStyle: 'normal',
			fontWeight: 400,
			lineHeight: 'normal',
		},
		pageNumberIndexContainerCSS: {
			display: 'none',
			// display: 'flex',
			// width: '68px',
			// height: '68px',
			// gap: '8px',
			// padding: '14px 10px 22px 10px',
			// justifyContent: 'center',
			// alignItems: 'center',
			// borderRadius: '999px',
			// border: '2px solid #333330',
			// background: '#333330',
			// alignSelf: 'center',
			// zIndex: 30,
			// position: 'absolute',
			// top: '160px',
		},
		contentCSS: {
			display: 'flex',
			flexDirection: 'column',
			gap: '10px',
			height: '210px',
			width: '100%',
			alignItems: 'center',
			textAlign: 'center',
			// marginTop: '88px',
		},
		subtopicCSS: {
			position: 'relative',
			zIndex: 30,
			maxHeight: '65px',
			textAlign: 'center',
		},
		columnCSS: {
			padding: '100px 40px 100px 40px',
			display: 'flex',
			flexDirection: 'column',
			gap: '20px',
			width: '100%',
			height: '100%',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		logoCSS: {
			zIndex: 30,
			position: 'relative',
			alignSelf: 'flex-end',
			maxWidth: '100px',
		},
	},
	First_page_img_1_casual_topic: {
		canvasCSS: {
			width: '100%',
			height: '100%',
			background: '#F1F1F1',
			// background: 'yellow',
			border: 'none',
		},
		columnCSS: {
			padding: '100px 40px 100px 40px',
			display: 'flex',
			flexDirection: 'column',
			width: '100%',
			height: '100%',
			alignItems: 'center',
			justifyContent: 'space-between',
			// maxHeight: '400px',
		},
		topicCSS: {
			position: 'relative',
			zIndex: 30,
			maxHeight: '135px',
			textAlign: 'center',
		},

		userNameCSS: {
			// paddingTop: '150px',
			zIndex: 30,
			position: 'relative',
			// maxWidth: '260px',
		},
		logoCSS: { zIndex: 30, position: 'relative', maxWidth: '100px' },
		indicatorCSS: {
			// zIndex: 30,
			// width: 'auto',
			display: 'none',
		},
		userNameAndLogoAndIndicatorBoxCSS: {
			display: 'flex',
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
			maxHeight: '100px',
			width: '100%',
			// position: 'relative',
			marginTop: '240px',
		},
		userNameAndLogoBoxCSS: {
			display: 'flex',
			flexDirection: 'row',
			// gap: '14px',
			alignItems: 'center',
			justifyContent: 'space-between',
			width: '100%',
		},
		imageContainerCSS: {
			// width: '274px',
			// height: '274px',
			// left: '50%',
			// top: '50%',
			// borderRadius: '999px',
			width: '400px',
			height: '400px',
			// opacity: '0.5',
			position: 'absolute',
			left: '50%',
			top: '40%',
			transform: 'translate(-50%, -50%)',
		},
	},
	//serious
	First_page_img_1_serious_subject: {
		canvasCSS: {
			width: '100%',
			height: '100%',
			background: '#F1F1F1',
			// background: 'yellow',
			border: 'none',
		},
		columnCSS: {
			padding: '100px 40px 100px 40px',
			display: 'flex',
			flexDirection: 'column',
			width: '100%',
			height: '100%',
			alignItems: 'center',
			justifyContent: 'space-between',
			// maxHeight: '400px',
		},
		originalTitleCSS: {
			position: 'relative',
			zIndex: 30,
			maxHeight: '135px',
			textAlign: 'center',
		},

		userNameCSS: {
			// paddingTop: '150px',
			zIndex: 30,
			position: 'relative',
			// maxWidth: '260px',
		},
		logoCSS: { zIndex: 30, position: 'relative', maxWidth: '100px' },
		indicatorCSS: {
			// zIndex: 30,
			// width: 'auto',
			display: 'none',
		},
		userNameAndLogoAndIndicatorBoxCSS: {
			display: 'flex',
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
			maxHeight: '100px',
			width: '100%',
			// position: 'relative',
			marginTop: '240px',
		},
		userNameAndLogoBoxCSS: {
			display: 'flex',
			flexDirection: 'row',
			// gap: '14px',
			alignItems: 'center',
			justifyContent: 'space-between',
			width: '100%',
		},
	},
	img_0_serious_subject: {
		canvasCSS: {
			width: '100%',
			height: '100%',
			background: '#F1F1F1',
			border: 'none',
		},
		horizontalDividerCSS: {
			display: 'none',
		},
		pageNumberIndexCSS: {
			color: '#F5F1E2',
			fontFamily: 'Georgia',
			fontSize: '42px',
			fontStyle: 'normal',
			fontWeight: 400,
			lineHeight: 'normal',
		},
		pageNumberIndexContainerCSS: {
			display: 'none',
			// display: 'flex',
			// width: '68px',
			// height: '68px',
			// gap: '8px',
			// padding: '14px 10px 22px 10px',
			// justifyContent: 'center',
			// alignItems: 'center',
			// borderRadius: '999px',
			// border: '2px solid #333330',
			// background: '#333330',
			// alignSelf: 'center',
			// zIndex: 30,
			// position: 'absolute',
			// top: '160px',
		},
		contentCSS: {
			display: 'flex',
			flexDirection: 'column',
			gap: '10px',
			height: '210px',
			width: '100%',
			alignItems: 'center',
			textAlign: 'center',
			// marginTop: '88px',
		},
		sectionTitleCSS: {
			position: 'relative',
			zIndex: 30,
			maxHeight: '65px',
			textAlign: 'center',
		},
		columnCSS: {
			padding: '100px 40px 100px 40px',
			display: 'flex',
			flexDirection: 'column',
			gap: '20px',
			width: '100%',
			height: '100%',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		logoCSS: {
			zIndex: 30,
			position: 'relative',
			alignSelf: 'flex-end',
			maxWidth: '100px',
		},
	},
	//reading notes
	First_page_img_1_reading_notes: {
		canvasCSS: {
			width: '100%',
			height: '100%',
			background: '#F1F1F1',
			// background: 'yellow',
			border: 'none',
		},
		columnCSS: {
			padding: '100px 40px 100px 40px',
			display: 'flex',
			flexDirection: 'column',
			width: '100%',
			height: '100%',
			alignItems: 'center',
			justifyContent: 'space-between',
			// maxHeight: '400px',
		},
		readingTitleCSS: {
			position: 'relative',
			zIndex: 30,
			maxHeight: '135px',
			textAlign: 'center',
		},

		userNameCSS: {
			// paddingTop: '150px',
			zIndex: 30,
			position: 'relative',
			// maxWidth: '260px',
		},
		logoCSS: { zIndex: 30, position: 'relative', maxWidth: '100px' },
		indicatorCSS: {
			// zIndex: 30,
			// width: 'auto',
			display: 'none',
		},
		userNameAndLogoAndIndicatorBoxCSS: {
			display: 'flex',
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
			maxHeight: '100px',
			width: '100%',
			// position: 'relative',
			marginTop: '240px',
		},
		userNameAndLogoBoxCSS: {
			display: 'flex',
			flexDirection: 'row',
			// gap: '14px',
			alignItems: 'center',
			justifyContent: 'space-between',
			width: '100%',
		},
		imageContainerCSS: {
			// width: '274px',
			// height: '274px',
			// left: '50%',
			// top: '50%',
			// borderRadius: '999px',
			width: '400px',
			height: '400px',
			// opacity: '0.5',
			position: 'absolute',
			left: '50%',
			top: '40%',
			transform: 'translate(-50%, -50%)',
			background: 'transparent',
		},
	},
	Col_1_img_0_reading_notes: {
		canvasCSS: {
			width: '100%',
			height: '100%',
			background: '#F1F1F1',
			border: 'none',
		},
		horizontalDividerCSS: {
			display: 'none',
		},

		sourceCSS: {
			// display: 'flex',
			// flexDirection: 'column',
			// gap: '10px',
			// height: '210px',
			width: '100%',
			// alignItems: 'center',
			textAlign: 'center',
			// marginTop: '88px',
		},
		quoteCSS: {
			position: 'relative',
			zIndex: 30,
			width: '100%',
			// maxHeight: '65px',
			textAlign: 'center',
		},
		columnCSS: {
			padding: '100px 40px 100px 40px',
			display: 'flex',
			flexDirection: 'column',
			gap: '20px',
			width: '100%',
			height: '100%',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		indicatorCSS: {
			display: 'none',
		},
		sourceAndLogoBoxCSS: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'center',
			width: '100%',
		},
		logoCSS: {
			zIndex: 30,
			position: 'relative',
			alignSelf: 'flex-end',
			// left: 0,
			// top: 0,
			maxWidth: '100px',
		},
	},
	Col_1_img_1_reading_notes: {
		canvasCSS: {
			width: '100%',
			height: '100%',
			background: '#F1F1F1',
			border: 'none',
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'center',
			padding: '100px 40px 100px 40px',
		},
		columnCSS: {
			// padding: '100px 40px 100px 40px',
			display: 'flex',
			flexDirection: 'column',
			gap: '20px',
			height: '100%',
			width: '100%',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		horizontalDividerCSS: {
			display: 'none',
		},
		pageNumberIndexCSS: {
			color: '#F5F1E2',
			fontFamily: 'Georgia',
			fontSize: '42px',
			fontStyle: 'normal',
			fontWeight: 400,
			lineHeight: 'normal',
		},
		pageNumberIndexContainerCSS: {
			display: 'none',
			// display: 'flex',
			// width: '68px',
			// height: '68px',
			// gap: '8px',
			// padding: '14px 10px 22px 10px',
			// justifyContent: 'center',
			// alignItems: 'center',
			// borderRadius: '999px',
			// border: '2px solid #333330',
			// background: '#333330',
			// alignSelf: 'center',
			// zIndex: 30,
			// position: 'absolute',
			// top: '160px',
		},
		quoteCSS: {
			position: 'relative',
			zIndex: 30,
			paddingLeft: '40px',
			paddingRight: '40px',
			// maxHeight: '65px',
			// marginTop: '200px',
			textAlign: 'center',
			maxHeight: '136px',
			// overflow: 'scroll',
		},
		imageAndTextContentContainerCSS: {
			// display: 'flex',
			// flexDirection: 'row',
			// display: 'grid',
			// gridTemplateColumns: 'repeat(2, minmax(0,1fr))', //
			// gap: '4px',
			width: '100%',
			// background: 'transparent',
			// marginTop: '34px',
			// height: '200px',
			// maxHeight: '400px',
		},
		imageContainerCSS: {
			// order: 0,
			// width: '100%',
			// height: '100%',
			// position: 'absolute',
			position: 'relative',
			height: '200px',
			width: '200px', // equivalent to w-full
			minHeight: '200px',
			// left: '50%',
			// top: '25%',
			// transform: 'translate(-50%, -50%)',
			background: 'transparent',
			// borderRadius:
			// 	'var(--radius-none, 0px) var(--radius-none, 0px) 96px var(--radius-none, 0px)',
			// border: '10px solid black',
		},
		indicatorCSS: {
			display: 'none',
		},

		sourceCSS: {
			display: 'flex',
			flexDirection: 'column',
			gap: '10px',
			// order: 1,
			maxHeight: '225px',
			// overflow: 'scroll', // if set, will cause editor tooltip hidden
			// marginTop: '34px',
			textAlign: 'center',
			alignItems: 'center',
		},
		sourceAndLogoBoxCSS: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'center',
			width: '100%',
		},
		logoCSS: {
			zIndex: 30,
			position: 'relative',
			alignSelf: 'flex-end',
			// left: 0,
			// top: 0,
			maxWidth: '100px',
		},
	},
	// last page
	last_page_layout: {
		canvasCSS: {
			width: '100%',
			height: '100%',
			background: '#F1F1F1',
			border: 'none',
		},
		columnCSS: {
			padding: '100px 40px 100px 40px',
			display: 'flex',
			flexDirection: 'column',
			width: '100%',
			height: '100%',
			// maxHeight: '400px',
		},
		lastPageTitleCSS: {
			position: 'relative',
			zIndex: 30,
			maxHeight: '135px',
		},
		lastPageContentCSS: {
			position: 'relative',
			zIndex: 30,
			display: 'flex',
			flexDirection: 'column',
			gap: '10px',
			marginTop: '40px',
			// marginBottom: '170px',
			height: '300px',
			// maxHeight: '400px',
			// overflow: 'scroll',
		},
		userNameCSS: {
			// paddingTop: '150px',
			zIndex: 30,
			position: 'relative',
			// maxWidth: '260px',
		},
		logoCSS: { zIndex: 30, position: 'relative', maxWidth: '100px' },
		indicatorCSS: {
			// zIndex: 30,
			// width: 'auto',
			display: 'none',
		},
		userNameAndLogoAndIndicatorBoxCSS: {
			display: 'flex',
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
			maxHeight: '100px',
			width: '100%',
			height: '100%',
			// position: 'relative',
			// marginTop: '240px',
		},
		userNameAndLogoBoxCSS: {
			display: 'flex',
			flexDirection: 'row',
			// gap: '14px',
			alignItems: 'center',
			justifyContent: 'space-between',
			width: '100%',
			height: '100%',
		},
	},
};
