'use client';

import React, { useState, useEffect, useRef } from 'react';
import { BigGrayButton } from './DrlambdaButton';
import { getImageDataUrl } from '../utils/DownloadImage';
import { SocialPostSlide } from '@/components/socialPost/socialPostHTML';
import SocialPostContainer from '@/components/socialPost/socialPostContainer';
import { templateDispatch as defaultTemplateDispatch } from '@/components/socialPost/socialPostTemplateDispatch';
import { templateDispatch as defaultTemplateDispatch2 } from '@/components/socialPost//socialPostTemplate2Dispatch';
import { templateDispatch as defaultTemplateDispatch3 } from '@/components/socialPost/socialPostTemplate3Dispatch';
import { templateDispatch as slideTemplateDispatch } from '@/components/slides/templateDispatch';
import Slide, { SlideKeys } from '@/models/Slide';
import SlideContainer from '../slides/SlideContainer';
import AuthService from '@/services/AuthService';
import ProjectService from '@/services/ProjectService';
import { FaTwitter } from "react-icons/fa";

type RepostButtonProps = {
    slides: SocialPostSlide[] | Slide[];
    post_type: string; //socialpost or slide
    setShare: (share:boolean) => void;
};

const RepostButton: React.FC<RepostButtonProps> = ({
    slides,
    post_type,
    setShare,
}) => {
    const [host, setHost] = useState('https://drlambda.ai');
    const [isProcessing, setIsProcessing] = useState(false);
    const [slideRef, setSlideRef] = useState(React.createRef<HTMLDivElement>());
    const [slideIndex, setSlideIndex] = useState(0)

    const project_id =
    typeof window !== 'undefined' && sessionStorage.project_id != undefined
        ? sessionStorage.project_id
        : '';

    const res_scenario =
    typeof sessionStorage !== 'undefined'
        ? sessionStorage.getItem('scenarioType')
        : '';

    useEffect(() => {
        if (
            window.location.hostname !== 'localhost' &&
            window.location.hostname !== '127.0.0.1'
        ) {
            setHost('https://' + window.location.hostname);
        } else {
            setHost(window.location.hostname);
        }
    }, []);

    const handleRepostToTwitter = async () => {
        try{
            setIsProcessing(true);
            const { userId, idToken: token } = await AuthService.getCurrentUserTokenAndId();
            //const publicImageUrl = await ProjectService.getSlideTwitterImg(project_id);
            //console.log(publicImageUrl)
            await ProjectService.repostSlideShareLink(token, project_id, setShare)
            const shareLink = `${host}/shared/${project_id}`
            const twitterText = 'Here is Slide generated by Drlambda\n\n';
            const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(twitterText)}${encodeURIComponent(shareLink)}`;
            window.open(twitterUrl, '_blank');
            setIsProcessing(false);
        } catch (error) {
            console.error('Failed to process Twitter repost:', error);
        }
    };
    
    function selectTemplateDispatch() {
		switch (res_scenario) {
			case 'casual_topic':
				return defaultTemplateDispatch;
			case 'serious_subject':
				return defaultTemplateDispatch2;
			case 'reading_notes':
				return defaultTemplateDispatch3;
			default:
				return defaultTemplateDispatch;
		}
	}

    // function selectPostType() {
    //     if (post_type === 'socialpost') {
    //         return (
    //             <SocialPostContainer
    //                 slides={slides as SocialPostSlide[]}
    //                 currentSlideIndex={0}
    //                 exportToPdfMode={true}
    //                 templateDispatch={selectTemplateDispatch()}
    //                 slideRef={slideRef}
    //                 onSlideRefUpdate={setSlideRef}
    //             />
    //         )
    //     }
    //     else if (post_type === 'slide') {
    //         return(
    //             <SlideContainer
    //                 slides={slides as Slide[]}
    //                 currentSlideIndex={0}
    //                 exportToPdfMode={true}
    //                 templateDispatch={slideTemplateDispatch}
    //                 slideRef={slideRef}
    //                 onSlideRefUpdate={setSlideRef}
    //             />
    //         )
    //     }
    //     else {
    //         console.error('invalid post type')
    //     }
    // }

    return (
        <div className='col-span-1 ml-3'>
            <BigGrayButton onClick={handleRepostToTwitter} isSubmitting={isProcessing}>
                <div className='flex flex-row items-center gap-x-2'>
                    Post to Twitter
                    <FaTwitter />
                </div>
            </BigGrayButton>

            {/* hidden div for export to pdf */}
            {/* <div className='absolute left-[-9999px] top-[-9999px] -z-1'>
                <div key={`exportToPdfContainer` + slideIndex.toString()}>
                     {selectPostType()}
                </div>
            </div> */}
            
        </div>
    );

};

export default RepostButton